pipeline {
    agent any

    stages {
        stage('Create Java File') {
            steps {
                // Create the HelloWorld.java file dynamically
                writeFile file: 'HelloWorld.java', text: '''
                    public class HelloWorld {
                        public static void main(String[] args) {
                            System.out.println("Hello, World!");
                        }
                    }
                '''
            }
        }

        stage('Build') {
            steps {
                // Compile the Java code
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                // Run the compiled Java code
                sh 'java HelloWorld'
            }
        }
    }

    post {
        success {
            echo 'Java Hello World program executed successfully!'
        }
        failure {
            echo 'Java Hello World program failed to execute.'
        }
    }
}
