pipeline {
    agent any
    
        stage('Build') {
            steps {
                sh 'javac HelloWorld.java'
            }
        }
        
        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }

    post {
        success {
            echo 'Java Hello World program executed successfully!'
        }
        failure {
            echo 'Java Hello World program failed to execute.'
        }
    }
}

